# Generated by Django 3.1 on 2021-01-27 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 27, 19, 44, 12, 64252, tzinfo=utc))),
            ],
        ),
    ]
